### PR TITLE
Fix #4

### LINKED ISSUE #4: Edge does not close its tabs
After running karma tests on edge, it does not close its tabs.

Making use of:
karma-webdriverio-launcher@0.0.1
karma-edge-launcher@0.4.2
Edge version: Microsoft Edge 42.17134.1.0

### PR DESCRIPTION
**Pull request by Itee**
Hi there,

This PR will fix #4 but make some changes (non breaking i think) about the logic.

It use two powershell scripts instead of the edge-launcher package wrapped into start and exit handlers to start and stop gracefully edge process.

I improved the units tests too and update them accordingly to the new features.

Hope this help.
Expecting your review and have a nice day !

### CODE REVIEW

**Comment by zzo** [comment]
please fix the PR to match our [conventions](http://karma-runner.github.io/latest/dev/git-commit-msg.html) thanks!

**Comment by Itee** [comment]
Mmmh sorry for that, i wasn't aware of it. I will update the PR.

I got some trouble about travis builds... due to the environement of build. How could i tell to travis that powershell is a pre-requis ?

**Comment by Itee** [comment]
I will create a new PR with updated commit messages. So i close this one.

**Comment by nickserv** [comment]
I haven't tried Travis on Windows, it might be easier to get it working on AppVeyor: https://ci.appveyor.com/project/nickmccurdy/karma-edge-launcher-ui7ax

I'll be sure to check out your new PR as this project has been kind of stagnant with the lack of edge-launcher updates. Thanks for your contribution!

**Comment by Itee** [comment]
@nickmccurdy You're welcome ! I just hope this will work, and go in the right way. I will take a look to appveyor.

**Comment by jslegers** [comment]
I didn't get either 0.4.2 or 0.4.3 to work as expected.

Version 0.4.2 closed Edge correctly, but open tabs were re-opened during the next run. This caused Edge to have X open tabs after X runs.

Version 0.4.3 failed to close Edge. And next run, Edge refused to start because it already was open.

I combined what worked in 0.4.2 with what worked in 0.4.3 and added some paths of [this script](https://www.nasvillanueva.com/reset-edge/), and now everything works as expected in my test environment.

With my changes, Edge now correctly starts with just one tab open every test run, and gets closed correctly afterwards.

For my changes, see https://github.com/karma-runner/karma-edge-launcher/pull/9

**Pull request closed without merging**
